apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nodejs-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: express
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/agiagoulas-express
    - name: image-repo
      value: quay.io/agiagoulas/express
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
          - ReadWriteOnce
