apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- name: quay.io/upslopeio/express-sample-app
  newName: quay.io/agiagoulas/express
  newTag: 249312ee88a7d8f34e8adaf03e59636452b21cc5
commonLabels:
  app.kubernetes.io/instance: express
  app.kubernetes.io/name: express
